### ISSUE TITLE
Add output for travel mode recommendation

### ISSUE THREAD

**Issue by Maxwell-lt** [CorporateMinions/your-next-trip#9]
- [x] Create a list of distance breakpoints for recommendations
- [x] Find images for each transportation type
- [x] Write blurb for each transportation type (travel speed, properties, fun facts)
- [x] Add JS code to display picture, blurb, and distance output (in miles?)

**Comment by Kbusch54** [comment]
walk under 2km
scooter under 10 km
drive under 600 km
fly

**Comment by Maxwell-lt** [comment]
All subtasks are complete
